version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-projeto-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672